name: Blockchain CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code to runner
        uses: actions/checkout@v2

      - name: Set up JS environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: npm run test
